### ISSUE TITLE
Annex D. CMAF Encoding for DASH-HLS Interop and manifest content

### ISSUE THREAD

**Issue by johnsim** [cta-wave/dash-hls#16]
The intended scope of this annex to the WAVE content spec was constraining CMAF content so that the same CMAF presentation can be described with either an HLS or a DASH manifest. Most of the identified constraints have to do with what CMAF changes are permitted at the splice points of a multi-period DASH presentation, but some  issues have been identified which involve the actual content in a manifest. For example, Issue cta-wave/dash-hls#15 notes the HLS manifest keyword EXT-X-DATERANGE must be match the payload of an EMSG box in the corresponding CMAF stream. Are their other examples where manifest content needs to be taken into consideration?

**Comment by technogeek00** [comment]
Review to ensure we've captured the above in both references and use-cases

**Comment by technogeek00** [comment]
We've captured the information on alignment of CMAF profiles here and terminology alignment will be updated post use case creation so that we have a good solid dictionary. The structure we will be following is:
- CMAF Profile description
- CMAF Authoring Restrictions
- DASH / HLS Manifest Conversions given restricted CMAF
