### ISSUE TITLE
HLS-DASH Interop: missing representation in adaptation set at period splice point

### ISSUE THREAD

**Issue by johnsim** [cta-wave/dash-hls#4]
D4.4 Representation Constraints
"In the case of a new Period with an Adaptation Set that has a missing Representation, a lower bandwidth Representation MAY be replicated as the missing Representation in the offered MPD." 

Will Law: Does not this force you in to ever decreasing bitrates? Consider the case of a live stream with bitrates of 1000, 2000 and 3000. We then insert an ad in a new period, which by this rule has bitrates of 500, 1000 and 2000. After that, we want to return to the primary content of 1000, 2000, 3000 but that contravenes this rule that the bandwidth must be <= the prior period?

**Comment by wilaw** [comment]
If your main program has 1000, 2000, 3000, 4000 bitrates , and the ad is available in 1050, 2050, 3050, 4050 - what do you do? By current rules, this should be a no-op. 

However one could argue two preferred responses
1. You could return an add with 1050, 2050 and 3050 (as these can all shown to be <= a program bitrate) 
2. You return 1050,2050,3050,4050 since the 50kbps is not a significant enough difference to affect the player.

**Comment by technogeek00** [comment]
Covered in #22
